resolver: lts-12.14
packages:
  - '.'
flags:
  snap-extras:
    "Examples": true
extra-deps:
  - digestive-functors-0.8.4.0
  - digestive-functors-heist-0.8.8.1
  - digestive-functors-snap-0.7.0.1
  - snap-1.1.1.0
  - heist-1.1.0.1
  - pwstore-fast-2.4.4
  - map-syntax-0.3
  - xmlhtml-0.2.5.2
  - blaze-html-0.9.1.1
  - blaze-markup-0.8.2.2
